### ISSUE TITLE
ClientSecret Auth not supported in shuffle DevOps task?

### ISSUE THREAD

**Issue by strwase** [Innofactor/Innofactor.Crm.CI#28]
Hi, 

when I try to use the shuffle import/export tasks using a ClientSecret connectionstring, I am unable to connect to power platform

![image](https://user-images.githubusercontent.com/10077785/105700047-93dc5680-5f08-11eb-9543-b85a2af2b102.png)

can It be the included crm sdk dll's need to be updated?

regards

**Comment by imranakram** [comment]
Hi, This was recently updated with the latest dependencies, however, it could be in need of some changes in the code. Is it something like this?

```
AuthType=ClientSecret;
  url=https://contosotest.crm.dynamics.com;
  ClientId={AppId};
  ClientSecret={ClientSecret}
```

**Comment by strwase** [comment]
that is indeed the format of connection string i'm using for which it's throwing an error

**Comment by strwase** [comment]
hi @imranakram , any updates on this. I'm still getting that error if I try to use a ClientSecrect connection string.

**Comment by imranakram** [comment]
Hi @strwase , I have narrowed down the problem now and will be opening a support case with Microsoft. Sorry about the delay, there's been a lot going on lately

**Comment by imranakram** [comment]
Hi @strwase , Please have a look at the latest version published. This should be fixed now.

**Comment by strwase** [comment]
> .

Hi @imranakram , I've just ran my pipeline in DevOps, still throws the same exception.

I've added the output below. As far as I can tell, the version number is still the same so I guess I'm still getting the old version of the task?

`    ##[debug]Evaluating condition for step: 'Export AdxExportDelta data'
    ##[debug]Evaluating: and(succeeded(), eq('Export', 'Export'))
    ##[debug]Evaluating and:
    ##[debug]..Evaluating succeeded:
    Version      : 9.0.5
    Author       : Innofactor Sweden
    Help         : 
    ==============================================================================
    ##[debug]VstsTaskSdk 0.8.0 commit 
    ##[debug]INPUT_DEFINITIONFILE: 'F:\DevOpsAgents\DevOpsAgent\_work\64\s\Shuffle Definitions\AdxExportDelta.xml'
    ##[debug]INPUT_DATAFILE: 'F:\DevOpsAgents\DevOpsAgent\_work\64\s\Shuffle Definitions\AdxExportDelta.data.xml'
    ##[debug]INPUT_SETVERSION: 'false'
    ##[debug] Converted to bool: False
    ##[debug]INPUT_CRMCONNECTIONSTRING: '***'
    ##[debug]Setting default data file
    ##[debug]Script Path    : F:\DevOpsAgents\DevOpsAgent\_work\_tasks\ShuffleExport_c0da7e50-d3a6-417e-9c8b-11da841352fc\9.0.5
    ##[debug]Definition Path: F:\DevOpsAgents\DevOpsAgent\_work\64\s\Shuffle Definitions
    ##[debug]Definition File: F:\DevOpsAgents\DevOpsAgent\_work\64\s\Shuffle Definitions\AdxExportDelta.xml
    ##[debug]Data File      : F:\DevOpsAgents\DevOpsAgent\_work\64\s\Shuffle Definitions\AdxExportDelta.data.xml
    ##[debug]Set Version    : False
    ##[debug]Connection String: ***
    Loading definition from F:\DevOpsAgents\DevOpsAgent\_work\64\s\Shuffle Definitions\AdxExportDelta.xml
    ##[debug]Importing DevUtils.CI: F:\DevOpsAgents\DevOpsAgent\_work\_tasks\ShuffleExport_c0da7e50-d3a6-417e-9c8b-11da841352fc\9.0.5\ps_modules\DevUtils.CI\Innofactor.Crm.CI.dll
    ##[debug]Loading module from path 'F:\DevOpsAgents\DevOpsAgent\_work\_tasks\ShuffleExport_c0da7e50-d3a6-417e-9c8b-11da841352fc\9.0.5\ps_modules\DevUtils.CI\Innofactor.Crm.CI.dll'.
    ##[debug]Importing cmdlet 'Update-CrmAssembly'.
    ##[debug]Importing cmdlet 'Export-CrmShuffle'.
    ##[debug]Importing cmdlet 'Import-CrmShuffle'.
    ##[debug]Importing cmdlet 'Update-CrmWebResources'.
    ##[debug]Importing cmdlet 'Select-WhoAmI'.
    ##[debug]Imported DevUtils.CI
    Starting export
    ##[debug]Current Security Protocol: Ssl3, Tls
    ##[debug]Modified Security Protocol: Ssl3, Tls, Tls11, Tls12
    ##[debug]Connecting to CRM
    ##[debug]Creating CrmServiceClient with: ***
    ##[debug]Caught exception from task script.
    ##[debug]Error record:
    ##[debug]Export-CrmShuffle : Connection not established. Last CRM error message:
    ##[debug]Unable to Login to Dynamics CRMOrganizationServiceProxy is null
    ##[debug]At F:\DevOpsAgents\DevOpsAgent\_work\_tasks\ShuffleExport_c0da7e50-d3a6-417e-9c8b-11da841352fc\9.0.5\ShuffleExport.ps1:51 char:13
    ##[debug]+ [xml]$exp = Export-CrmShuffle -ConnectionString $ConnectionString -De ...
    ##[debug]+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ##[debug]    + CategoryInfo          : InvalidArgument: (:) [Export-CrmShuffle], PSArgumentException
    ##[debug]    + FullyQualifiedErrorId : Argument,Cinteros.Crm.Utils.CI.Cmdlets.ExportCrmShuffleCmdlet
    ##[debug] 
    ##[debug]Script stack trace:
    ##[debug]at <ScriptBlock>, F:\DevOpsAgents\DevOpsAgent\_work\_tasks\ShuffleExport_c0da7e50-d3a6-417e-9c8b-11da841352fc\9.0.5\ShuffleExport.ps1: line 51
    ##[debug]at <ScriptBlock>, <No file>: line 1
    ##[debug]at <ScriptBlock>, <No file>: line 22
    ##[debug]at <ScriptBlock>, <No file>: line 18
    ##[debug]at <ScriptBlock>, <No file>: line 1
    ##[debug]Exception:
    ##[debug]System.Management.Automation.PSArgumentException: Connection not established. Last CRM error message:
    ##[debug]Unable to Login to Dynamics CRMOrganizationServiceProxy is null
    ##[debug]   at Cinteros.Crm.Utils.CI.Cmdlets.XrmCommandBase.BeginProcessing()
    ##[debug]   at System.Management.Automation.Cmdlet.DoBeginProcessing()
    ##[debug]   at System.Management.Automation.CommandProcessorBase.DoBegin()
    ##[error]Connection not established. Last CRM error message:
    Unable to Login to Dynamics CRMOrganizationServiceProxy is null
    ##[debug]Processed: ##vso[task.logissue type=error]Connection not established. Last CRM error message:%0AUnable to Login to Dynamics CRMOrganizationServiceProxy is null
    ##[debug]Processed: ##vso[task.complete result=Failed]
    Finishing: Export AdxExportDelta data
`

**Comment by imranakram** [comment]
@strwase Publishing another update after updating `task.json`'s for cmdlets. Found out they also have to be updated via this discussion: https://github.com/MicrosoftDocs/azure-devops-docs/issues/4087#issuecomment-517267853

**Comment by strwase** [comment]
Hi @imranakram, updating the task version fixed it.
however, now I'm getting an exception in the logic itself
    
    ##[debug]System.ArgumentNullException: String reference not set to an instance of a String.
    ##[debug]   at System.Reflection.RuntimeAssembly.GetResource(RuntimeAssembly assembly, String resourceName, UInt64& length, StackCrawlMarkHandle stackMark, Boolean skipSecurityCheck)
    ##[debug]   at System.Reflection.RuntimeAssembly.GetManifestResourceStream(String name, StackCrawlMark& stackMark, Boolean skipSecurityCheck)
    ##[debug]   at System.Reflection.RuntimeAssembly.GetManifestResourceStream(String name)
    ##[debug]   at Cinteros.Crm.Utils.Shuffle.ShuffleHelper.LoadDefinitionSchemas()
    ##[debug]   at Cinteros.Crm.Utils.Shuffle.ShuffleHelper.get_Schemas()
    ##[debug]   at Cinteros.Crm.Utils.Shuffle.ShuffleHelper.ValidateDefinitionXml(IExecutionContainer container, XmlDocument def)
    ##[debug]   at Cinteros.Crm.Utils.Shuffle.ShuffleHelper.ValidateDefinitionXml(XmlDocument def)
    ##[debug]   at Cinteros.Crm.Utils.Shuffle.Shuffler.set_Definition(XmlDocument value)
    ##[debug]   at Cinteros.Crm.Utils.Shuffle.Shuffler.QuickExport(IExecutionContainer container, XmlDocument Definition, SerializationType Type, Char Delimeter, EventHandler`1 ShuffleEventHandler, String defpath, Boolean clearRemainingShuffleVars)
    ##[debug]   at Innofactor.Crm.CI.Cmdlets.ExportCrmShuffle.ProcessRecord()
    
Did anything change in the logic itself which could be causing this?

**Comment by imranakram** [comment]
Thanks, it could be some difference introduced when we refactored shuffle to replace the underlying DevUtils. Please give it a try in the Shuffle Runner XTB plugin. This needs manual installation though.

**Comment by strwase** [comment]
I think you've got an issue in your code on line 395 of  [ShuffleDataExport.cs](https://github.com/Innofactor/Innofactor.Crm.CI/blob/master/shared/Innofactor.Crm.Shuffle/ShuffleDataExport.cs)

you put 2 placeholders in the fetchxml but they never get replaced with a value, so the retrievemultiple fails with an Invalid XML error

> fetch = fetch.Replace("<fetch ", "<fetch {0} {1} ");

So either you're missing a part of the implementation, or this line is redundant.

**Comment by imranakram** [comment]
@strwase I'm working on trying to figure this out. Apparently this code has been there for a very long time.

**Comment by imranakram** [comment]
@strwase I've published another update :)

**Comment by strwase** [comment]
hi @imranakram , in azure I'm still getting the error, if I run it with visual studio, it works fine, so I'm guessing something went wrong with the publish to Azure DevOps.

**Comment by imranakram** [comment]
@strwase I've updated task versions and published another update. Hope this one works. If not, please post with the log

**Comment by strwase** [comment]
@imranakram, Sorry man, still the same error.

I can see the version has updated, but the same exception is still thrown. 
Maybe an old version of the assembly is getting packaged?

    ##[debug]Evaluating condition for step: 'Export AdxExportDelta data'
    ##[debug]Evaluating: and(succeeded(), eq('Export', 'Export'))
    ##[debug]Evaluating and:
    ##[debug]..Evaluating succeeded:
    ##[debug]..=> True
    ##[debug]..Evaluating eq:
    ##[debug]....Evaluating String:
    ##[debug]....=> 'Export'
    ##[debug]....Evaluating String:
    ##[debug]....=> 'Export'
    ##[debug]..=> True
    ##[debug]=> True
    ##[debug]Expanded: and(True, eq('Export', 'Export'))
    ##[debug]Result: True
    Starting: Export AdxExportDelta data
    ==============================================================================
    Task         : Innofactor DevOps: Shuffle Export
    Description  : Export data and solutions using Innofactor Shuffle.
    Version      : 9.0.8
    Author       : Innofactor Sweden
    Help         : 
    ==============================================================================
    ##[debug]VstsTaskSdk 0.11.0 commit 7ff27a3e0bdd6f7b06690ae5f5b63cb84d0f23f4
    ##[debug]INPUT_DEFINITIONFILE: 'F:\DevOpsAgents\DevOpsAgent\_work\64\s\Shuffle Definitions\AdxExportDelta.xml'
    ##[debug]INPUT_DATAFILE: 'F:\DevOpsAgents\DevOpsAgent\_work\64\s\Shuffle Definitions\AdxExportDelta.data.xml'
    ##[debug]INPUT_SETVERSION: 'false'
    ##[debug] Converted to bool: False
    ##[debug]INPUT_CRMCONNECTIONSTRING: '***'
    ##[debug]Setting default data file
    ##[debug]Script Path    : F:\DevOpsAgents\DevOpsAgent\_work\_tasks\ShuffleExport_c0da7e50-d3a6-417e-9c8b-11da841352fc\9.0.8
    ##[debug]Definition Path: F:\DevOpsAgents\DevOpsAgent\_work\64\s\Shuffle Definitions
    ##[debug]Definition File: F:\DevOpsAgents\DevOpsAgent\_work\64\s\Shuffle Definitions\AdxExportDelta.xml
    ##[debug]Data File      : F:\DevOpsAgents\DevOpsAgent\_work\64\s\Shuffle Definitions\AdxExportDelta.data.xml
    ##[debug]Set Version    : False
    ##[debug]Connection String: ***
    Loading definition from F:\DevOpsAgents\DevOpsAgent\_work\64\s\Shuffle Definitions\AdxExportDelta.xml
    ##[debug]Importing CI module from: F:\DevOpsAgents\DevOpsAgent\_work\_tasks\ShuffleExport_c0da7e50-d3a6-417e-9c8b-11da841352fc\9.0.8\ps_modules\CI\Innofactor.Crm.CI.dll
    ##[debug]Loading module from path 'F:\DevOpsAgents\DevOpsAgent\_work\_tasks\ShuffleExport_c0da7e50-d3a6-417e-9c8b-11da841352fc\9.0.8\ps_modules\CI\Innofactor.Crm.CI.dll'.
    ##[debug]Importing cmdlet 'Export-CrmShuffle'.
    ##[debug]Importing cmdlet 'Import-CrmShuffle'.
    ##[debug]CI module was successfully imported
    Starting export
    ##[debug]Current Security Protocol: Ssl3, Tls
    ##[debug]Modified Security Protocol: Ssl3, Tls, Tls11, Tls12
    ##[debug]Connecting to CRM/Dataverse
    ##[debug]Attempting to connect with: ***
    ##[debug]Connecting to CRM/Dataverse [attempt 1]
    ##[debug]Exporting
    ##[debug] [START of QuickExport]
    ##[debug]Caught exception from task script.
    ##[debug]Error record:
    ##[debug]Export-CrmShuffle : String reference not set to an instance of a String.
    ##[debug]At F:\DevOpsAgents\DevOpsAgent\_work\_tasks\ShuffleExport_c0da7e50-d3a6-417e-9c8b-11da841352fc\9.0.8\script.ps1:54 char:13
    ##[debug]+ [xml]$exp = Export-CrmShuffle -ConnectionString $ConnectionString -De ...
    ##[debug]+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ##[debug]    + CategoryInfo          : ReadError: (System.Xml.XmlDocument:XmlDocument) [Export-CrmShuffle], ArgumentNullExcepti    on
    ##[debug]    + FullyQualifiedErrorId : QuickExport,Innofactor.Crm.CI.Cmdlets.ExportCrmShuffle
    ##[debug] 
    ##[debug]Script stack trace:
    ##[debug]at <ScriptBlock>, F:\DevOpsAgents\DevOpsAgent\_work\_tasks\ShuffleExport_c0da7e50-d3a6-417e-9c8b-11da841352fc\9.0.8\script.ps1: line 54
    ##[debug]at <ScriptBlock>, <No file>: line 1
    ##[debug]at <ScriptBlock>, <No file>: line 22
    ##[debug]at <ScriptBlock>, <No file>: line 18
    ##[debug]at <ScriptBlock>, <No file>: line 1
    ##[debug]Exception:
    ##[debug]System.ArgumentNullException: String reference not set to an instance of a String.
    ##[debug]   at System.Reflection.RuntimeAssembly.GetResource(RuntimeAssembly assembly, String resourceName, UInt64& length, StackCrawlMarkHandle stackMark, Boolean skipSecurityCheck)
    ##[debug]   at System.Reflection.RuntimeAssembly.GetManifestResourceStream(String name, StackCrawlMark& stackMark, Boolean skipSecurityCheck)
    ##[debug]   at System.Reflection.RuntimeAssembly.GetManifestResourceStream(String name)
    ##[debug]   at Cinteros.Crm.Utils.Shuffle.ShuffleHelper.LoadDefinitionSchemas()
    ##[debug]   at Cinteros.Crm.Utils.Shuffle.ShuffleHelper.get_Schemas()
    ##[debug]   at Cinteros.Crm.Utils.Shuffle.ShuffleHelper.ValidateDefinitionXml(IExecutionContainer container, XmlDocument def)
    ##[debug]   at Cinteros.Crm.Utils.Shuffle.ShuffleHelper.ValidateDefinitionXml(XmlDocument def)
    ##[debug]   at Cinteros.Crm.Utils.Shuffle.Shuffler.set_Definition(XmlDocument value)
    ##[debug]   at Cinteros.Crm.Utils.Shuffle.Shuffler.QuickExport(IExecutionContainer container, XmlDocument Definition, SerializationType Type, Char Delimeter, EventHandler`1 ShuffleEventHandler, String defpath, Boolean clearRemainingShuffleVars)
    ##[debug]   at Innofactor.Crm.CI.Cmdlets.ExportCrmShuffle.ProcessRecord()
    ##[error]String reference not set to an instance of a String.
    ##[debug]Processed: ##vso[task.logissue type=error]String reference not set to an instance of a String.
    ##[debug]Processed: ##vso[task.complete result=Failed]

**Comment by imranakram** [comment]
@strwase Please try again, I've got a successful build now.

**Comment by strwase** [comment]
@imranakram, embedding the resources idd fixed the issue, thank you for the help!
